-- AlterTable
ALTER TABLE `playlists` ADD COLUMN `date_updated` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `removed_songs` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `total_songs` INTEGER NOT NULL DEFAULT 0;
