name: Deploy Mémoire [Reve] Server

on:
    push:
        branches:
            - master
        paths:
            - 'reve/**'

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '21' # Use your Node.js version

            - name: Install dependencies
              run: |
                  cd reve
                  npm install

            - name: Build project
              run: |
                  cd reve
                  npm run build

            - name: Deploy to gh-pages
              run: |
                  git config user.name "MiVladie"
                  git config user.email "MiVladie@users.noreply.github.com"
                  git add -f reve/build  # Add the build folder from 'reve'
                  git commit -m "Deploy to gh-pages"
                  git subtree push --prefix reve/build origin gh-pages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
